name: build
on: [workflow_dispatch]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - run: sudo apt install -y xorg-dev libgl1-mesa-dev
        if: matrix.os == 'ubuntu-latest'

      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - run: npm i
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}
          path: ./build/Release/*.node